name       : q4wine
version    : 1.3.5
release    : 6
source     :
    - https://ncu.dl.sourceforge.net/project/q4wine/q4wine/q4wine%201.3.5/q4wine-1.3.5.tar.bz2 : aa48b0ea8ff504e341b3352194380aa256f6ac8a6a301e1bbf30196eec8d310c
license    : GPL-3.0
summary    : Qt GUI for Wine
component  : virt
description: |
    Q4Wine is a Qt GUI for wine. It will help you manage wine prefixes and installed applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - icoutils
rundeps    :
    - icoutils
    - sqlite3
    - wine
setup      : |
    %cmake . -DQT5=ON -DUSE_BZIP2=ON -DQT_RCC_EXECUTABLE:PATH=/usr/bin/rcc
build      : |
    %make
install    : |
    %make_install
