name       : q4wine
version    : 1.1.2
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/q4wine/q4wine/q4wine%201.1-r2/q4wine-1.1-r2.tar.bz2 : 01463f9ec3ef9f7ef987d2b77425f2806cf2b60f574deb6644458366782eafc7
license    : GPL-3.0
summary    : QT4 GUI for Wine
description: |
    Q4Wine is a qt4 GUI for wine. It will help you manage wine prefixes and installed applications.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(icon-naming-utils)
setup      : |
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    %cmake . -DWITH_ICOUTILS=OFF
build      : |
    %make
install    : |
    %make_install
