name       : q4wine
version    : 1.3.5
release    : 5
source     :
    - https://ncu.dl.sourceforge.net/project/q4wine/q4wine/q4wine%201.3.5/q4wine-1.3.5.tar.bz2 : aa48b0ea8ff504e341b3352194380aa256f6ac8a6a301e1bbf30196eec8d310c
license    : GPL-3.0
summary    : QT4 GUI for Wine
component  : virt
description: |
    Q4Wine is a qt4 GUI for wine. It will help you manage wine prefixes and installed applications.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(icon-naming-utils)
setup      : |
    %cmake . -DWITH_ICOUTILS=OFF -DQT_RCC_EXECUTABLE:PATH=/usr/bin/rcc-qt4
build      : |
    %make
install    : |
    %make_install
