name       : q4wine
version    : 1.3.10
release    : 8
source     :
    - https://kent.dl.sourceforge.net/project/q4wine/q4wine/q4wine%201.3.10/q4wine-1.3.10.tar.bz2 : e022e745f16fc28a00b2cb7c51c7728f72dc5088ad9caef7ccf563231973fd52
license    : GPL-3.0-or-later
summary    : Qt GUI for Wine
component  : virt
description: |
    Q4Wine is a Qt GUI for wine. It will help you manage wine prefixes and installed applications.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - icoutils
rundeps    :
    - icoutils
    - qt5-svg
    - sqlite3
    - wine
setup      : |
    %cmake . -DQT5=ON -DUSE_GZIP=ON -DQT_RCC_EXECUTABLE:PATH=/usr/bin/rcc
build      : |
    %make
install    : |
    %make_install
