name       : q4wine
version    : 1.3.2
release    : 3
source     :
    - http://ncu.dl.sourceforge.net/project/q4wine/q4wine/q4wine%201.3.2/q4wine-1.3.2.tar.bz2 : 3c3fca6de6de19c6497ac1cad667d2f4525f4e849edc4fbfe77061c612b381d2
license    : GPL-3.0
summary    : QT4 GUI for Wine
component  : virt
description: |
    Q4Wine is a qt4 GUI for wine. It will help you manage wine prefixes and installed applications.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(icon-naming-utils)
setup      : |
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    %cmake . -DWITH_ICOUTILS=OFF
build      : |
    %make
install    : |
    %make_install
